substitutions:
  name: athom-smart-plug-v3-5090ec
  friendly_name: Yale proxy plug

packages:
  Athom_Technology.Smart_Plug_V3: github://athom-tech/esp32-configs/athom-smart-plug.yaml

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:
  encryption:
    key: !secret yale_plug_api_key

ota:
  - platform: web_server
