substitutions:
  name: athom-smart-plug-v3-50e884
  friendly_name: Water cooker power plug
packages:
  Athom_Technology.Smart_Plug_V3: github://athom-tech/esp32-configs/athom-smart-plug.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: !secret water_cooker_api_key


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
