substitutions:
  name: athom-smart-plug-v3-50cc3c
  friendly_name: Wine fridge power plug
packages:
  Athom_Technology.Smart_Plug_V3: github://athom-tech/esp32-configs/athom-smart-plug.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: !secret wine_fridge_api_key


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
